theme: jekyll-theme-cayman

# from https://github.com/hbrls/jekyll-gitbook
title: Unofficial Grid.ai Tips and Tricks
description: Unofficial Grid.ai Tips and Tricks
show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]